name: Continuous Delivery

on:
  push:
    branches:
      - main

env:
  NAMESPACE: ${{ secrets.NAMESPACE }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  APP_ID: ${{ secrets.APP_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
        
    - name: Configure gcd
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
    - name: Build Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/$APP_ID:1.0.0 .
        docker tag us-central1-docker.pkg.dev/$PROJECT_ID/$APP_ID:1.0.0 $NAMESPACE/$APP_ID:1.0.0
      
    - name: Push Docker Image
      run: docker push us-central1-docker.pkg.dev/$PROJECT_ID/$APP_ID:1.0.0
        
    - name: Deploy
      run: gcloud run deploy $APP_ID --image us-central1-docker.pkg.dev/$PROJECT_ID/$APP_ID:1.0.0
    
    - name: Run stress test
      run: make stress-test
