name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        APP_ID: ${{ secrets.APP_ID }}
        export_default_credentials: true

    - name: Configure gcd
      run: |
        echo $GOOGLE_APPLICATION_CREDENTIALS > key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t $PROJECT_ID/$APP_ID:1.0.0 .
        docker push $PROJECT_ID/$APP_ID:1.0.0
        gcloud run deploy $APP_ID --image $PROJECT_ID/$APP_ID:1.0.0
    
    - name: Run stress test
      run: make stress-test
